import "./globals.css";
import type { Metadata } from "next";
import Image from 'next/image';
import linkedInImg from "../../public/images/linkedIN.svg";
import gitImg from "../../public/images/github-mark-white.svg";
import GoogleAnalytics from "./GoogleAnalytics";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleAnalytics GA_TRACKING_ID={process.env.GA_TRACKING_ID as string} />
      <body className="bg-gray-300">
        <nav className="bg-slate-800 p-4 text-black text-right flex">
          <a
            className="rounded-lg px-3 py-2 font-medium hover:scale-125 cursor-pointer"
            href="https://github.com/urvesh21"
            target="_blank"
          >
            <Image
              className="w-9 h-9"
              src={gitImg}
              height={144}
              width={144}
              alt="Urvesh Patel"
            />
          </a>
          <a
            className="rounded-lg px-3 py-2 font-medium hover:scale-125 cursor-pointer"
            href="https://www.linkedin.com/in/urvesh-patel-805a26a6/"
            target="_blank"
          >
            <Image
              className="w-10 h-10"
              src={linkedInImg}
              height={144}
              width={144}
              alt="Urvesh Patel"
            />
          </a>
          <a
            className="rounded-full bg-cyan-500 font-bold p-4 ml-auto"
            href="./downloadFiles/UrveshPatel2023.docx.pdf"
            download
            target="_blank"
          >
            Download
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
