import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-300">
        <nav className="bg-cyan-600 p-4 text-black">Hey There</nav>
        {children}
      </body>
    </html>
  );
}
